"""Game state: colony room, contracts, production, hauls."""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from .constants import (
    ARK_POPULATION,
    DAYS_PER_MONTH,
    SECONDS_PER_DAY,
    SEED_FE_TONNES,
)
from .orbits import transfer_options
from .system_gen import StarSystem, build_survey_archive, generate_system
from .tech import (
    BUILDINGS,
    HAB_OPTIONS,
    POWER_OPTIONS,
    RECIPES,
    RESOURCE_NAMES,
    UNIT_BUILDS,
    expand_base_plan,
    tech_book_summary,
)


def _id() -> str:
    return uuid.uuid4().hex[:10]


@dataclass
class Contract:
    id: str
    project_id: str
    title: str
    resource: str
    amount_t: float
    delivered_t: float = 0.0
    status: str = "open"  # open, filled, cancelled
    note: str = ""

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "project_id": self.project_id,
            "title": self.title,
            "resource": self.resource,
            "resource_name": RESOURCE_NAMES.get(self.resource, self.resource),
            "amount_t": round(self.amount_t, 2),
            "delivered_t": round(self.delivered_t, 2),
            "remaining_t": round(max(0.0, self.amount_t - self.delivered_t), 2),
            "status": self.status,
            "note": self.note,
        }


@dataclass
class Project:
    id: str
    name: str
    body_id: str
    power_id: str
    hab_id: str
    materials: Dict[str, float]
    buildings: List[str]
    status: str = "active"

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "body_id": self.body_id,
            "power_id": self.power_id,
            "hab_id": self.hab_id,
            "materials": self.materials,
            "buildings": self.buildings,
            "status": self.status,
        }


@dataclass
class Haul:
    id: str
    origin_id: str
    dest_id: str
    resource: str
    amount_t: float
    option_name: str
    propellant_t: float
    months_total: float
    months_left: float
    dv_m_s: float
    status: str = "in_flight"  # in_flight, arrived

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "origin_id": self.origin_id,
            "dest_id": self.dest_id,
            "resource": self.resource,
            "amount_t": round(self.amount_t, 2),
            "option_name": self.option_name,
            "propellant_t": round(self.propellant_t, 2),
            "months_total": round(self.months_total, 2),
            "months_left": round(self.months_left, 2),
            "dv_m_s": round(self.dv_m_s, 1),
            "status": self.status,
        }


@dataclass
class Site:
    body_id: str
    buildings: List[str] = field(default_factory=list)
    stockpile: Dict[str, float] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {"body_id": self.body_id, "buildings": self.buildings, "stockpile": {k: round(v, 2) for k, v in self.stockpile.items()}}


# Capability tags a unit can apply to a target body
CAP_SURVEY = "survey"
CAP_MINE = "mine"
CAP_HAUL = "haul"
CAP_BUILD = "build"  # ark / construction focus
CAP_COMMAND = "command"


@dataclass
class FleetUnit:
    id: str
    name: str
    kind: str  # ark | survey | miner | hauler
    location_id: str  # body id or "transit"
    status: str = "idle"  # idle | en_route | working
    order: str = ""
    target_id: str = ""
    months_left: float = 0.0
    capabilities: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "kind": self.kind,
            "location_id": self.location_id,
            "status": self.status,
            "order": self.order,
            "target_id": self.target_id,
            "months_left": round(self.months_left, 2),
            "capabilities": self.capabilities,
        }


@dataclass
class BuildJob:
    """Ark fabrication job — materials already reserved from stock."""
    id: str
    unit_kind: str
    name: str
    months_total: float
    months_left: float
    capabilities: List[str]
    status: str = "building"  # building | complete

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "unit_kind": self.unit_kind,
            "name": self.name,
            "months_total": round(self.months_total, 2),
            "months_left": round(self.months_left, 2),
            "capabilities": self.capabilities,
            "status": self.status,
        }


class Game:
    """Single colony room — continuous going-concern simulation."""

    def __init__(self, universe_seed: int = 20260727) -> None:
        self.phase = "menu"  # menu | transit | system
        self.system: Optional[StarSystem] = None
        # Pre-existing remote dossiers (not generated by a player "scan" click)
        self.survey_archive: List[dict] = build_survey_archive(8, universe_seed=universe_seed)
        self.catalog: List[dict] = []  # currently viewed archive slice
        self.archive_opened: bool = False
        self.sim_time_s: float = 0.0
        self.wall_anchor: float = time.time()
        self.last_wall: float = self.wall_anchor
        self.events: List[dict] = []
        self.projects: Dict[str, Project] = {}
        self.contracts: Dict[str, Contract] = {}
        self.hauls: Dict[str, Haul] = {}
        self.sites: Dict[str, Site] = {}
        self.fleet: Dict[str, FleetUnit] = {}
        self.build_queue: List[BuildJob] = []
        self._unit_seq: Dict[str, int] = {"survey": 0, "miner": 0, "hauler": 0}
        # Ark inventory (materials / seed stock — specialized gear is built later)
        self.ark_stock: Dict[str, float] = {
            "Fe": SEED_FE_TONNES,
            "Al": 200.0,
            "Si": 150.0,
            "H2O": 500.0,
            "CH4": 80.0,
            "O2": 120.0,
            "steel": 100.0,
            "chip": 40.0,
            "panel": 20.0,
            "chem_prop": 60.0,
            "Xe": 0.0,  # spent on arrival
        }
        self.population = ARK_POPULATION
        self.selected_seed: Optional[int] = None
        self.transit_months_left: float = 0.0
        self.message: str = (
            "Humanity is a going concern. Open the survey archive to review "
            "remote dossiers, then commit a destination."
        )
        self.scanned: set[str] = set()
        self.auto_warp_votes = 0
        self.home_body_id: str = ""

    # --- time ---
    def catch_up(self) -> float:
        """Advance sim from wall clock. Returns months advanced."""
        now = time.time()
        dt = max(0.0, now - self.last_wall)
        self.last_wall = now
        if self.phase == "menu":
            return 0.0
        # Believable sky: live clock is slow. 1 wall second ≈ 1 game day / 7
        # (Earth year ~ 42 wall minutes). Use Warp for logistics jumps.
        game_dt_s = dt * (SECONDS_PER_DAY / 7.0)
        return self.advance(game_dt_s)

    def advance(self, game_dt_s: float) -> float:
        if game_dt_s <= 0:
            return 0.0
        self.sim_time_s += game_dt_s
        months = game_dt_s / (SECONDS_PER_DAY * DAYS_PER_MONTH)

        if self.phase == "transit":
            self.transit_months_left = max(0.0, self.transit_months_left - months)
            if self.transit_months_left <= 0:
                self._arrive()
            return months

        if self.phase != "system":
            return months

        for h in list(self.hauls.values()):
            if h.status != "in_flight":
                continue
            h.months_left -= months
            if h.months_left <= 0:
                self._complete_haul(h)

        for u in list(self.fleet.values()):
            if u.status == "en_route" and u.months_left > 0:
                u.months_left -= months
                if u.months_left <= 0:
                    self._complete_unit_order(u)
            elif u.status == "working" and u.order == "survey":
                # Continuous survey: learn more the longer you sit
                self._tick_survey(u, months)
            elif u.status == "working" and u.order == "mine" and u.months_left > 0:
                u.months_left -= months
                if u.months_left <= 0:
                    self._complete_unit_order(u)

        self._tick_builds(months)
        # No auto ark consumption of seed stock. Sites tick only with buildings.
        self._site_tick(months)
        return months

    def _tick_builds(self, months: float) -> None:
        for job in list(self.build_queue):
            if job.status != "building":
                continue
            job.months_left -= months
            if job.months_left <= 0:
                job.months_left = 0.0
                job.status = "complete"
                self._finish_build(job)
        self.build_queue = [j for j in self.build_queue if j.status == "building"]

    def _finish_build(self, job: BuildJob) -> None:
        home = self.home_body_id or (
            self.sites.get("ark_orbit").body_id if self.sites.get("ark_orbit") else "p0"
        )
        self._unit_seq[job.unit_kind] = self._unit_seq.get(job.unit_kind, 0) + 1
        n = self._unit_seq[job.unit_kind]
        uid = f"{job.unit_kind[0:2]}{n}"
        name = f"{job.name} {n}"
        self.fleet[uid] = FleetUnit(
            id=uid,
            name=name,
            kind=job.unit_kind,
            location_id=home,
            capabilities=list(job.capabilities),
        )
        self._log("build", f"Fabrication complete: {name} ready at ark.")

    def queue_build(self, unit_kind: str) -> dict:
        """Authorize ark to build a unit from seed materials + time."""
        self.catch_up()
        if self.phase != "system":
            raise ValueError("can only build after arrival")
        spec = UNIT_BUILDS.get(unit_kind)
        if not spec:
            raise ValueError(f"unknown unit type {unit_kind}")
        # Must have ark present
        if not any(u.kind == "ark" for u in self.fleet.values()):
            raise ValueError("no ark")
        for res, need in spec["cost"].items():
            have = self.ark_stock.get(res, 0.0)
            if have + 1e-9 < need:
                raise ValueError(f"need {need} t {res}, ark has {have:.1f}")
        for res, need in spec["cost"].items():
            self.ark_stock[res] = self.ark_stock.get(res, 0.0) - need
        job = BuildJob(
            id=_id(),
            unit_kind=spec["kind"],
            name=spec["name"],
            months_total=float(spec["months"]),
            months_left=float(spec["months"]),
            capabilities=list(spec["capabilities"]),
        )
        self.build_queue.append(job)
        self._log(
            "build",
            f"Authorized build: {spec['name']} "
            f"({spec['months']} mo, materials reserved).",
        )
        return self.snapshot()

    def warp_to_next_event(self) -> dict:
        """Advance to next meaningful event (orders, builds, survey slice)."""
        self.catch_up()
        targets: List[float] = []
        if self.phase == "transit" and self.transit_months_left > 0:
            targets.append(self.transit_months_left)
        for h in self.hauls.values():
            if h.status == "in_flight" and h.months_left > 0:
                targets.append(h.months_left)
        for job in self.build_queue:
            if job.status == "building" and job.months_left > 0:
                targets.append(job.months_left)
        for u in self.fleet.values():
            if u.status == "en_route" and u.months_left > 0:
                targets.append(u.months_left)
            elif u.status == "working" and u.order == "mine" and u.months_left > 0:
                targets.append(u.months_left)
            elif u.status == "working" and u.order == "survey":
                # Warp survey in 1-month slices so discoveries surface gradually
                targets.append(1.0)
        if not targets:
            # Small nudge: 1 week of game time (world still advances)
            self.advance(SECONDS_PER_DAY * 7)
            self._log("event", "No pending orders — advanced 1 week.")
            return {"warped_months": 7.0 / DAYS_PER_MONTH, "reason": "idle_nudge"}
        m = min(targets)
        self.advance(m * SECONDS_PER_DAY * DAYS_PER_MONTH)
        self.auto_warp_votes += 1
        self._log("event", f"Warped {m:.2f} months to next order/event.")
        return {"warped_months": m, "reason": "next_event"}

    def _log(self, kind: str, text: str) -> None:
        self.events.insert(
            0,
            {
                "id": _id(),
                "t_months": self.sim_time_s / (SECONDS_PER_DAY * DAYS_PER_MONTH),
                "kind": kind,
                "text": text,
            },
        )
        self.events = self.events[:100]
        self.message = text

    # --- menu / transit ---
    def open_survey_archive(self) -> List[dict]:
        """
        View pre-existing remote survey dossiers.
        Does not invent systems — archive was fixed when the room was created.
        """
        self.archive_opened = True
        self.catalog = list(self.survey_archive)
        self.message = (
            f"Survey archive open: {len(self.catalog)} remote dossiers on file "
            f"(colonial deep-space network)."
        )
        return self.catalog

    def refresh_catalog(self) -> List[dict]:
        """Legacy name — opens the going-concern survey archive."""
        return self.open_survey_archive()

    def select_star(self, seed: int) -> dict:
        # Must match a dossier (going concern), not an arbitrary invent
        dossier = next((d for d in self.survey_archive if d["seed"] == seed), None)
        if dossier is None:
            # Allow if archive not filtered yet but seed is in opened catalog
            dossier = next((d for d in self.catalog if d.get("seed") == seed), None)
        if dossier is None:
            raise ValueError("unknown dossier — open the survey archive and pick a star on file")
        self.selected_seed = seed
        self.system = generate_system(seed=seed)
        self.transit_months_left = 12.0 * (8.0 + self.system.difficulty)  # ~8–18 years
        self.phase = "transit"
        self.sim_time_s = 0.0
        self.last_wall = time.time()
        label = dossier.get("dossier_id") or seed
        self._log(
            "transit",
            f"Committed to dossier {label} ({self.system.star.get('name', seed)}). "
            f"Transit ~{self.transit_months_left/12:.1f} years. Xe reserved for capture.",
        )
        return self.snapshot()

    def _arrive(self) -> None:
        self.phase = "system"
        self.ark_stock["Xe"] = 0.0
        assert self.system
        home = next(
            (b for b in self.system.bodies if b.kind == "planet" and b.planet_class == "rocky"),
            next(b for b in self.system.bodies if b.kind == "planet"),
        )
        self.home_body_id = home.id
        self.sites["ark_orbit"] = Site(body_id=home.id, buildings=["ark"], stockpile={})
        self._spawn_arrival_ark(home.id)
        self._log(
            "arrival",
            f"Capture complete at {home.name}. Xe tanks dry. "
            f"Ark holds people and seed materials — authorize builds for survey craft and industry gear.",
        )

    def _spawn_arrival_ark(self, home_id: str) -> None:
        """Materials-only arrival: ark only, no pre-built specialized fleet."""
        self.fleet.clear()
        self.build_queue.clear()
        self.fleet["ark"] = FleetUnit(
            id="ark",
            name="Colony Ark",
            kind="ark",
            location_id=home_id,
            capabilities=[CAP_COMMAND, CAP_BUILD, CAP_HAUL],
        )

    def _heliocentric_radius_m(self, body_id: str) -> float:
        """Orbital radius about the star for travel planning (moons use parent planet)."""
        assert self.system
        if body_id in ("ark", "ark_orbit"):
            site = self.sites.get("ark_orbit")
            body_id = site.body_id if site else next(b.id for b in self.system.bodies if b.kind == "planet")
        b = self.system.body_by_id(body_id)
        if not b:
            raise ValueError("unknown body")
        if b.kind == "moon" and b.parent_id:
            parent = self.system.body_by_id(b.parent_id)
            return parent.semi_major_m if parent else b.semi_major_m
        return b.semi_major_m

    def _travel_months(self, from_id: str, to_id: str, unit_kind: str = "hauler") -> float:
        """
        Cruise time from orbital mechanics (Hohmann between heliocentric radii).
        Survey sats are low-thrust → longer than a chemical hauler.
        Same planet / local moon still takes real local time — no teleport.
        """
        from .orbits import hohmann_transfer
        from .constants import DAYS_PER_MONTH, SECONDS_PER_DAY

        assert self.system
        if from_id == to_id:
            # Already there: still not instant (station-keeping / phasing)
            return 0.25 if unit_kind == "survey" else 0.1

        fb = self.system.body_by_id(from_id) if from_id not in ("ark", "ark_orbit") else None
        tb = self.system.body_by_id(to_id)

        # Local transfer: same planet system (planet ↔ its moon, or moon ↔ moon of same parent)
        def planet_key(body_id: str, body) -> Optional[str]:
            if body is None and body_id in ("ark", "ark_orbit"):
                site = self.sites.get("ark_orbit")
                return site.body_id if site else None
            if body is None:
                return body_id
            if body.kind == "moon":
                return body.parent_id
            return body.id

        if tb and planet_key(from_id, fb) == planet_key(to_id, tb):
            # Days–weeks to change moon orbits / lander loiter — not interplanetary
            local = 0.4 if unit_kind == "survey" else 0.25
            # Slightly longer if going to/from a different moon
            if fb and tb and fb.kind == "moon" and tb.kind == "moon" and fb.id != tb.id:
                local += 0.2
            return local

        r1 = self._heliocentric_radius_m(from_id)
        r2 = self._heliocentric_radius_m(to_id)
        # Avoid identical radii numerical issue
        if abs(r1 - r2) / max(r1, r2) < 0.01:
            return 0.5

        _dv, tof_s = hohmann_transfer(r1, r2, self.system.star_mu)
        months = tof_s / (SECONDS_PER_DAY * DAYS_PER_MONTH)

        # Hohmann is the *minimum-energy* coast. Add synodic-ish wait fudge for departure
        # window (player doesn't micro the date): ~10–20% of TOF, min 0.5 mo.
        window = max(0.5, 0.15 * months)

        # Low-thrust survey sats: longer than pure Hohmann chemical
        if unit_kind == "survey":
            months *= 1.65
            window *= 1.1
        elif unit_kind == "miner":
            months *= 1.25

        total = months + window
        # Floor: even "nearby" neighbors take real time
        return max(0.75, total)

    def estimate_order(self, unit_id: str, order: str, target_id: str = "") -> dict:
        """UI helper: how long will this order take?"""
        u = self.fleet.get(unit_id)
        if not u or not self.system:
            return {"months": 0, "travel_months": 0, "work_months": 0}
        work = 0.0
        if order == "survey":
            # Transit only — survey continues until recalled (no one-shot dump)
            work = 0.0
        elif order == "mine":
            work = 1.5  # shift once a site exists
        elif order == "move":
            work = 0.0
        elif order == "idle":
            return {"months": 0, "travel_months": 0, "work_months": 0}
        # target_id for mine may be a mine_site id
        dest_body = target_id
        if order == "mine" and self.system:
            site = self._find_mine_site(target_id)
            if site:
                dest_body = site.body_id
        travel = self._travel_months(u.location_id, dest_body, u.kind) if dest_body else 0.0
        if order == "idle":
            travel = 0.0
        note = ""
        if order == "survey":
            note = "Then stays on station; detail improves over months until you recall it."
        return {
            "months": round(travel + work, 2),
            "travel_months": round(travel, 2),
            "work_months": round(work, 2),
            "years": round((travel + work) / 12.0, 2),
            "note": note,
        }

    def _find_mine_site(self, site_id: str):
        if not self.system:
            return None
        for b in self.system.bodies:
            for s in b.mine_sites:
                if s.id == site_id:
                    return s
        return None

    def _tick_survey(self, u: FleetUnit, months: float) -> None:
        assert self.system
        body = self.system.body_by_id(u.location_id)
        if not body:
            return
        notes = body.apply_survey_time(months)
        self.scanned.add(body.id)
        if notes:
            self._log("scan", f"{u.name} @ {body.name} ({body.survey_months:.1f} mo): " + "; ".join(notes))

    def issue_order(self, unit_id: str, order: str, target_id: str = "") -> dict:
        """
        Apply a unit's capability to a target: survey | mine | move.
        Survey: go there and stay — knowledge deepens with time; mine sites unlock.
        Mine: requires a *found* mine site (not the whole planet).
        """
        self.catch_up()
        u = self.fleet.get(unit_id)
        if not u:
            raise ValueError("unknown unit")
        # Busy if en_route with time left, or mining shift, or surveying (must idle first)
        if u.status == "en_route" and u.months_left > 0:
            raise ValueError(f"{u.name} is en route")
        if u.status == "working" and u.order == "mine" and u.months_left > 0:
            raise ValueError(f"{u.name} is mining")
        if u.status == "working" and u.order == "survey" and order != "idle":
            raise ValueError(f"{u.name} is surveying — stand by (idle) to reassign")
        assert self.system

        if order == "idle":
            u.status = "idle"
            u.order = ""
            u.target_id = ""
            u.months_left = 0.0
            self._log("order", f"{u.name}: standing by.")
            return self.snapshot()

        if order == "survey":
            if CAP_SURVEY not in u.capabilities:
                raise ValueError("unit cannot survey")
            body = self.system.body_by_id(target_id)
            if not body:
                raise ValueError("pick a body to survey")
            travel = self._travel_months(u.location_id, target_id, u.kind)
            u.order = "survey"
            u.target_id = target_id
            if travel <= 0.3 and u.location_id == target_id:
                # Already on station — start surveying immediately
                u.status = "working"
                u.months_left = 0.0
                self._log(
                    "order",
                    f"{u.name} begins search for extraction sites on {body.name}. "
                    f"Stays until recalled; a mineable site appears only after enough detail.",
                )
            else:
                u.status = "en_route"
                u.months_left = travel
                self._log(
                    "order",
                    f"{u.name} → {body.name} to find extraction sites: {travel:.1f} mo transit, "
                    f"then continuous survey until recalled.",
                )
            return self.snapshot()

        if order == "mine":
            if CAP_MINE not in u.capabilities:
                raise ValueError("unit cannot mine")
            # target_id must be a mine_site id (unlocked by survey)
            msite = self._find_mine_site(target_id)
            if not msite:
                raise ValueError(
                    "no mine site selected — survey until a suitable location is found, "
                    "then mine that site (not the whole world)"
                )
            body = self.system.body_by_id(msite.body_id)
            travel = self._travel_months(u.location_id, msite.body_id, u.kind)
            work = 1.5
            u.order = "mine"
            u.target_id = msite.id  # site id
            u.status = "en_route"
            u.months_left = travel + work
            self._log(
                "order",
                f"{u.name} → mine {msite.name} on {body.name if body else msite.body_id}: "
                f"{travel:.1f} mo transit + {work:.1f} mo shift.",
            )
            return self.snapshot()

        if order == "move":
            body = self.system.body_by_id(target_id)
            if not body:
                raise ValueError("pick a destination")
            travel = self._travel_months(u.location_id, target_id, u.kind)
            u.order = "move"
            u.target_id = target_id
            u.status = "en_route"
            u.months_left = max(0.75, travel)
            self._log(
                "order",
                f"{u.name} → {body.name}: {u.months_left:.1f} mo transit (~{u.months_left/12:.2f} y).",
            )
            return self.snapshot()

        raise ValueError(f"unknown order {order}")

    def _complete_unit_order(self, u: FleetUnit) -> None:
        assert self.system
        if u.order == "move":
            u.location_id = u.target_id
            u.status = "idle"
            u.order = ""
            body = self.system.body_by_id(u.location_id)
            self._log("order", f"{u.name} arrived at {body.name if body else u.location_id}.")
            u.target_id = ""
            u.months_left = 0.0
            return

        if u.order == "survey":
            # Arrived on station — begin continuous survey (does not dump full map)
            u.location_id = u.target_id
            body = self.system.body_by_id(u.target_id)
            u.status = "working"
            u.months_left = 0.0
            self._log(
                "scan",
                f"{u.name} on station at {body.name if body else u.target_id}. "
                f"Surveying… knowledge will grow over time. Recall with Stand by.",
            )
            # Small initial pass so warp immediately can show first hints
            if body:
                notes = body.apply_survey_time(0.25)
                self.scanned.add(body.id)
                if notes:
                    self._log("scan", f"{u.name}: " + "; ".join(notes))
            return

        if u.order == "mine":
            msite = self._find_mine_site(u.target_id)
            if not msite:
                u.status = "idle"
                u.order = ""
                u.months_left = 0.0
                self._log("mine", f"{u.name}: mine site gone.")
                return
            u.location_id = msite.body_id
            body = self.system.body_by_id(msite.body_id)
            site = self.sites.setdefault(msite.body_id, Site(body_id=msite.body_id))
            took = min(msite.amount_t, 50.0 * msite.grade)
            msite.amount_t -= took
            # also draw down body deposit pool
            if body:
                for dep in body.deposits:
                    if dep.resource == msite.resource:
                        dep.amount_t = max(0.0, dep.amount_t - took)
            site.stockpile[msite.resource] = site.stockpile.get(msite.resource, 0.0) + took
            self._log(
                "mine",
                f"{u.name} extracted {took:.0f} t {msite.resource} at {msite.name} "
                f"({msite.region}). Site remaining ~{msite.amount_t:.0f} t.",
            )
            u.status = "idle"
            u.order = ""
            u.target_id = ""
            u.months_left = 0.0
            return

        u.status = "idle"
        u.months_left = 0.0

    # --- scan / base plans ---
    def scan_body(self, body_id: str) -> dict:
        """Legacy helper: instant survey via first free survey sat, or error."""
        free = next((u for u in self.fleet.values() if CAP_SURVEY in u.capabilities and u.status == "idle"), None)
        if not free:
            raise ValueError("no idle survey unit — select a survey sat and order Survey")
        return self.issue_order(free.id, "survey", body_id)

    def plan_base(self, body_id: str, power_id: str, hab_id: str, name: str = "") -> dict:
        self.catch_up()
        assert self.system
        body = self.system.body_by_id(body_id)
        if not body:
            raise ValueError("unknown body")
        if power_id not in POWER_OPTIONS or hab_id not in HAB_OPTIONS:
            raise ValueError("bad options")
        plan = expand_base_plan(power_id, hab_id)
        pid = _id()
        project = Project(
            id=pid,
            name=name or f"Base on {body.name}",
            body_id=body_id,
            power_id=power_id,
            hab_id=hab_id,
            materials=dict(plan["materials"]),
            buildings=list(plan["buildings"]),
        )
        self.projects[pid] = project
        if body_id not in self.sites:
            self.sites[body_id] = Site(body_id=body_id)

        # Spawn contracts — contextual ore vs refined
        site = self.sites[body_id]
        has_refinery = "refinery" in site.buildings or "refinery" in project.buildings
        for res, amt in project.materials.items():
            if amt <= 0:
                continue
            note = ""
            req = res
            # If they need steel and will build refinery / have Fe deposit, prefer Fe ore contract too
            if res == "steel" and has_refinery:
                # split: contract steel from ark + Fe ore local
                self._add_contract(pid, f"Deliver steel (bootstrap)", "steel", amt * 0.35, "Ark or import refined steel to start.")
                self._add_contract(pid, f"Mine iron ore for refinery", "Fe", amt * 1.2, "Local ore once extractor is up; refinery converts to steel.")
                continue
            if res == "panel":
                note = "Ark can trickle panels, or fab locally once online."
            if res == "magnet" or res in ("He", "fusion_fuel", "radiator"):
                note = "Long path — visible, not blocked by research. Expect years."
            self._add_contract(pid, f"Supply {RESOURCE_NAMES.get(res, res)}", req, amt, note)

        # Building kits themselves
        for b in project.buildings:
            bt = BUILDINGS.get(b)
            if not bt:
                continue
            for res, amt in bt.build_cost.items():
                self._add_contract(pid, f"Build {bt.name}: {RESOURCE_NAMES.get(res, res)}", res, amt, f"Construction inputs for {bt.name}.")

        self._log("project", f"Project '{project.name}' created — contracts opened from needs.")
        return self.snapshot()

    def _add_contract(self, project_id: str, title: str, resource: str, amount: float, note: str) -> None:
        cid = _id()
        self.contracts[cid] = Contract(
            id=cid,
            project_id=project_id,
            title=title,
            resource=resource,
            amount_t=amount,
            note=note,
        )

    def deliver_from_ark(self, contract_id: str, amount_t: Optional[float] = None) -> dict:
        """Fill contract from ark stock (instant local orbital transfer abstraction for bootstrap)."""
        self.catch_up()
        c = self.contracts.get(contract_id)
        if not c or c.status != "open":
            raise ValueError("bad contract")
        need = c.amount_t - c.delivered_t
        have = self.ark_stock.get(c.resource, 0.0)
        give = min(need, have, amount_t if amount_t is not None else need)
        if give <= 0:
            raise ValueError(f"ark has no {c.resource}")
        self.ark_stock[c.resource] = have - give
        c.delivered_t += give
        # material goes to site stockpile
        proj = self.projects[c.project_id]
        site = self.sites.setdefault(proj.body_id, Site(body_id=proj.body_id))
        site.stockpile[c.resource] = site.stockpile.get(c.resource, 0.0) + give
        if c.delivered_t >= c.amount_t - 1e-6:
            c.status = "filled"
            c.delivered_t = c.amount_t
            self._try_complete_project(proj)
        self._log("deliver", f"Ark delivered {give:.1f} t {c.resource} toward '{c.title}'.")
        return self.snapshot()

    def _try_complete_project(self, proj: Project) -> None:
        related = [c for c in self.contracts.values() if c.project_id == proj.id]
        if related and all(c.status == "filled" for c in related):
            site = self.sites[proj.body_id]
            for b in proj.buildings:
                if b not in site.buildings:
                    site.buildings.append(b)
            proj.status = "complete"
            self._log("project", f"Project complete: {proj.name}. Buildings online: {', '.join(proj.buildings)}.")

    # --- hauls ---
    def haul_options(self, origin_id: str, dest_id: str) -> List[dict]:
        """
        Ark/orbital haulers start in space. Cost ≈ interplanetary Hohmann
        + a partial destination landing burn (surface well still matters).
        Hauler dry mass kept modest so seed chem_prop can close early loops.
        """
        assert self.system
        o = self._radius_of(origin_id)
        d = self._radius_of(dest_id)
        extra = 0.0
        dest = self.system.body_by_id(dest_id)
        if dest and dest.kind in ("planet", "moon", "asteroid"):
            from .orbits import dv_surface_to_orbit

            # Landing / surface delivery leg (not full SSTO both ways)
            extra += 0.35 * dv_surface_to_orbit(dest.mass_kg, dest.radius_m)
        # Avoid identical radii (same orbit) — tiny hop
        if abs(o - d) / max(o, d) < 0.02:
            o *= 0.98
        opts = transfer_options(
            o, d, self.system.star_mu, ship_dry_mass_t=8.0, extra_dv_m_s=extra, isp_s=340.0
        )
        return [x.to_dict() for x in opts]

    def _radius_of(self, body_id: str) -> float:
        assert self.system
        if body_id in ("ark", "ark_orbit"):
            site = self.sites.get("ark_orbit")
            body_id = site.body_id if site else next(
                (b.id for b in self.system.bodies if b.kind == "planet"),
                self.system.bodies[0].id,
            )
        b = self.system.body_by_id(body_id)
        if not b:
            raise ValueError("unknown body")
        if b.kind == "moon":
            parent = self.system.body_by_id(b.parent_id) if b.parent_id else None
            return parent.semi_major_m if parent else b.semi_major_m
        return b.semi_major_m

    def start_haul(
        self,
        origin_id: str,
        dest_id: str,
        resource: str,
        amount_t: float,
        option_index: int = 0,
        contract_id: Optional[str] = None,
    ) -> dict:
        self.catch_up()
        opts = self.haul_options(origin_id, dest_id)
        if not opts or option_index < 0 or option_index >= len(opts):
            raise ValueError("bad transfer option")
        opt = opts[option_index]
        # take cargo + propellant from origin stock (ark or site)
        stock = self._stock_for(origin_id)
        if stock.get(resource, 0.0) < amount_t:
            raise ValueError(f"insufficient {resource} at origin")
        prop = opt["propellant_t"]
        if stock.get("chem_prop", 0.0) < prop:
            raise ValueError(f"need {prop:.1f} t chem_prop for this transfer; have {stock.get('chem_prop', 0):.1f}")
        stock[resource] -= amount_t
        stock["chem_prop"] -= prop
        hid = _id()
        self.hauls[hid] = Haul(
            id=hid,
            origin_id=origin_id,
            dest_id=dest_id,
            resource=resource,
            amount_t=amount_t,
            option_name=opt["name"],
            propellant_t=prop,
            months_total=opt["months"],
            months_left=opt["months"],
            dv_m_s=opt["dv_m_s"],
        )
        if contract_id:
            # remember linkage in note via events
            self._log("haul", f"Haul {amount_t:.1f} t {resource} via {opt['name']} ({opt['months']:.1f} mo, {prop:.1f} t prop). Linked contract {contract_id}.")
        else:
            self._log("haul", f"Haul {amount_t:.1f} t {resource} via {opt['name']} ({opt['months']:.1f} mo, {prop:.1f} t prop).")
        # stash contract id on haul via dynamic attr
        self.hauls[hid].__dict__["contract_id"] = contract_id
        return self.snapshot()

    def _stock_for(self, location_id: str) -> Dict[str, float]:
        if location_id in ("ark", "ark_orbit"):
            return self.ark_stock
        site = self.sites.setdefault(location_id, Site(body_id=location_id))
        return site.stockpile

    def _complete_haul(self, h: Haul) -> None:
        h.status = "arrived"
        h.months_left = 0.0
        dest_stock = self._stock_for(h.dest_id if h.dest_id != "ark_orbit" else "ark")
        if h.dest_id in ("ark", "ark_orbit"):
            dest_stock = self.ark_stock
        else:
            site = self.sites.setdefault(h.dest_id, Site(body_id=h.dest_id))
            dest_stock = site.stockpile
        dest_stock[h.resource] = dest_stock.get(h.resource, 0.0) + h.amount_t
        cid = h.__dict__.get("contract_id")
        if cid and cid in self.contracts:
            c = self.contracts[cid]
            if c.status == "open":
                room = c.amount_t - c.delivered_t
                apply = min(room, h.amount_t)
                c.delivered_t += apply
                if c.delivered_t >= c.amount_t - 1e-6:
                    c.status = "filled"
                    proj = self.projects.get(c.project_id)
                    if proj:
                        self._try_complete_project(proj)
        self._log("haul", f"Haul arrived: {h.amount_t:.1f} t {h.resource} → {h.dest_id}.")

    def _ark_tick(self, months: float) -> None:
        """Slow ark recipes if inputs available."""
        for rid in ("ark_steel", "ark_chip", "ark_panel", "ark_prop"):
            recipe = RECIPES[rid]
            # fractional batches
            batches = months / max(recipe.months, 1e-6)
            if batches <= 0:
                continue
            # limit by inputs
            max_b = batches
            for res, need in recipe.inputs.items():
                have = self.ark_stock.get(res, 0.0)
                if need > 0:
                    max_b = min(max_b, have / need)
            if max_b <= 1e-9:
                continue
            for res, need in recipe.inputs.items():
                self.ark_stock[res] = self.ark_stock.get(res, 0.0) - need * max_b
            for res, out in recipe.outputs.items():
                self.ark_stock[res] = self.ark_stock.get(res, 0.0) + out * max_b

    def _site_tick(self, months: float) -> None:
        if not self.system:
            return
        for site in self.sites.values():
            if site.body_id == "ark_orbit":
                continue
            body = self.system.body_by_id(site.body_id)
            if not body:
                continue
            if "extractor" in site.buildings:
                for dep in body.deposits:
                    if not dep.known or dep.amount_t <= 0:
                        continue
                    rate = 20.0 * dep.grade  # t/month
                    took = min(dep.amount_t, rate * months)
                    dep.amount_t -= took
                    site.stockpile[dep.resource] = site.stockpile.get(dep.resource, 0.0) + took
            if "refinery" in site.buildings and site.stockpile.get("Fe", 0) > 0:
                recipe = RECIPES["refine_fe"]
                batches = months / recipe.months
                max_b = min(batches, site.stockpile.get("Fe", 0) / 1.2)
                if max_b > 0:
                    site.stockpile["Fe"] -= 1.2 * max_b
                    site.stockpile["steel"] = site.stockpile.get("steel", 0) + 1.0 * max_b
            if "scoop" in site.buildings and body.has_atmosphere and "CH4" in (body.atmosphere_note or "CH4"):
                site.stockpile["CH4"] = site.stockpile.get("CH4", 0) + 8.0 * months
            # also allow scoop if deposit CH4 known
            if "scoop" in site.buildings:
                for dep in body.deposits:
                    if dep.known and dep.resource == "CH4" and dep.amount_t > 0:
                        took = min(dep.amount_t, 15.0 * months)
                        dep.amount_t -= took
                        site.stockpile["CH4"] = site.stockpile.get("CH4", 0) + took

    def snapshot(self) -> dict:
        self.catch_up()
        months = self.sim_time_s / (SECONDS_PER_DAY * DAYS_PER_MONTH)
        data: Dict[str, Any] = {
            "phase": self.phase,
            "message": self.message,
            "sim_months": round(months, 3),
            "sim_years": round(months / 12.0, 3),
            "population": self.population,
            "ark_stock": {k: round(v, 2) for k, v in self.ark_stock.items()},
            "events": self.events[:30],
            "catalog": self.catalog,
            "archive_opened": self.archive_opened,
            "survey_archive_count": len(self.survey_archive),
            "projects": [p.to_dict() for p in self.projects.values()],
            "contracts": [c.to_dict() for c in self.contracts.values()],
            "hauls": [h.to_dict() for h in self.hauls.values()],
            "fleet": [u.to_dict() for u in self.fleet.values()],
            "builds": [j.to_dict() for j in self.build_queue],
            "sites": {k: v.to_dict() for k, v in self.sites.items()},
            "scanned": list(self.scanned),
            "tech": tech_book_summary(),
            "unit_builds": UNIT_BUILDS,
            "transit_months_left": round(self.transit_months_left, 2),
            "build_options": {
                "power": {k: {"name": v["name"], "description": v["description"]} for k, v in POWER_OPTIONS.items()},
                "hab": {k: {"name": v["name"], "description": v["description"]} for k, v in HAB_OPTIONS.items()},
            },
        }
        if self.system:
            data["system"] = self.system.to_dict(self.sim_time_s)
        return data


# Global room (solo host)
ROOM = Game()
